-- AUTH-001 step 1: the SP owns the channel vocabulary, and a phone login can be relayed by email.
--
-- Until a paid SMS/WhatsApp sender exists (AUTH-001 D1/D2), Go asks sp_request_otp to relay a phone
-- channel: the same call finds the active user holding that phone and returns their email, so the
-- relay costs no extra query. The OTP row still records the phone and its channel, which is what
-- sp_verify_otp matches on — verify does not change.
--
-- sp_invalidate_otp closes a stored code whose delivery failed (store before send), so a code that
-- never reached anyone cannot be guessed against.
--
-- The signature and the result change, so DROP + CREATE (sql.md).

DROP FUNCTION IF EXISTS auth.sp_request_otp(VARCHAR, VARCHAR, VARCHAR);

CREATE FUNCTION auth.sp_request_otp(
    p_destination VARCHAR,                  -- phone or email, as the user typed it
    p_otp_channel VARCHAR,                  -- whatsapp | sms | email
    p_otp_code VARCHAR,                     -- 6-digit code generated by Go
    p_relay_to_email BOOLEAN DEFAULT FALSE  -- phone channel delivered to the account's email
)
RETURNS TABLE (
    otp_id UUID,
    destination VARCHAR,
    channel VARCHAR,
    expires_at TIMESTAMP WITH TIME ZONE,
    relay_email VARCHAR
) LANGUAGE plpgsql AS $$
DECLARE
    v_destination VARCHAR := TRIM(p_destination);
    v_channel VARCHAR := LOWER(TRIM(p_otp_channel));
    v_relay_email VARCHAR;
    v_otp_id UUID;
    v_expires_at TIMESTAMP WITH TIME ZONE := CURRENT_TIMESTAMP + interval '10 minutes';
BEGIN
    IF v_destination IS NULL OR v_destination = '' THEN
        RAISE EXCEPTION 'otp.destination.invalid'
            USING ERRCODE = 'O0001', DETAIL = 'Destination (phone or email) is required';
    END IF;

    IF v_channel IS NULL OR v_channel NOT IN ('whatsapp', 'sms', 'email') THEN
        RAISE EXCEPTION 'otp.channel.invalid'
            USING ERRCODE = 'O0002', DETAIL = 'OTP channel must be whatsapp, sms or email';
    END IF;

    IF p_otp_code IS NULL OR p_otp_code !~ '^\d{6}$' THEN
        RAISE EXCEPTION 'otp.code.invalid'
            USING ERRCODE = 'O0003', DETAIL = 'OTP code must be exactly 6 digits';
    END IF;

    IF p_relay_to_email THEN
        IF v_channel = 'email' THEN
            RAISE EXCEPTION 'otp.channel.invalid'
                USING ERRCODE = 'O0002', DETAIL = 'Only a phone channel can be relayed by email';
        END IF;

        SELECT u.email INTO v_relay_email
        FROM auth.users u
        WHERE u.phone = v_destination
          AND u.is_active = TRUE
          AND u.email IS NOT NULL
        LIMIT 1;

        IF v_relay_email IS NULL THEN
            RAISE EXCEPTION 'otp.phone.not-registered'
                USING ERRCODE = 'O0007', DETAIL = 'No account holds this phone; sign in with email';
        END IF;
    END IF;

    INSERT INTO auth.otp_requests (destination, otp_channel, otp_code, expires_at)
    VALUES (v_destination, v_channel, p_otp_code, v_expires_at)
    RETURNING id INTO v_otp_id;

    RETURN QUERY SELECT v_otp_id, v_destination, v_channel, v_expires_at, v_relay_email;
END;
$$;

CREATE FUNCTION auth.sp_invalidate_otp(p_otp_id UUID)
RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
    UPDATE auth.otp_requests
    SET invalidated_at = CURRENT_TIMESTAMP,
        updated_at = CURRENT_TIMESTAMP
    WHERE id = p_otp_id
      AND invalidated_at IS NULL;
END;
$$;
