version: "3"
services:
  web-app:
    image: golang:1.23.0-alpine3.20
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MIGRATE_DATABASE_URL=postgres://postgres:postgres@db:5432/web?sslmode=disable
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
    depends_on:
      - db
    ports:
      - "8080:8080"  # Exponemos el puerto en el contenedor y en el host
    networks:
      - app-network

  db:
    image: postgres:alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
