version: "3"
services:
  web-app:
    image: golang:1.17-alpine
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MIGRATE_DATABASE_URL=postgres://postgres:postgres@db:5432/web?sslmode=disable
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
    depends_on:
      - db
    # Agrega una etiqueta de red para comunicarse con Nginx
    networks:
      - app-network

  db:
    image: postgres:alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    # Configura Nginx para actuar como proxy inverso hacia el contenedor de la aplicación Go
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web-app
    # Agrega una etiqueta de red para comunicarse con la aplicación Go
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
