services:
  # ============ PLATFORM API (Admin) ============
  platform-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GO_MAIN: platform
    ports:
      - "8080:8080"
    depends_on:
      - platform-db
    env_file:
      - .env.platform
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8080

  platform-db:
    image: postgres:16-alpine
    restart: always
    container_name: platform-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  # ============ TENANT API (Business) ============
  tenant-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GO_MAIN: tenant
    ports:
      - "9080:9080"
    depends_on:
      - tenant-db
    env_file:
      - .env.tenant
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=9080

  tenant-db:
    image: postgres:16-alpine
    restart: always
    container_name: tenant-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tenant_db
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
