DROP FUNCTION IF EXISTS tracking.sp_create_route(UUID, UUID, VARCHAR, VARCHAR, VARCHAR, VARCHAR, UUID, DECIMAL, DECIMAL, DECIMAL, DECIMAL, VARCHAR, TIME, TIME, INT);
DROP FUNCTION IF EXISTS tracking.sp_update_route(UUID, UUID, VARCHAR, UUID, BOOLEAN);
DROP FUNCTION IF EXISTS tracking.sp_list_routes(UUID, UUID, BOOLEAN);
DROP FUNCTION IF EXISTS tracking.sp_get_route(UUID, UUID);
DROP FUNCTION IF EXISTS tracking.sp_delete_route(UUID, UUID);
