DROP FUNCTION IF EXISTS tracking.sp_create_company(UUID, VARCHAR, VARCHAR, VARCHAR, TEXT, VARCHAR, VARCHAR, VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS tracking.sp_update_company(UUID, UUID, VARCHAR, VARCHAR, VARCHAR, TEXT, VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS tracking.sp_list_companies(UUID, VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS tracking.sp_get_company(UUID, UUID);
DROP FUNCTION IF EXISTS tracking.sp_delete_company(UUID, UUID);
