DROP FUNCTION IF EXISTS tracking.sp_create_vehicle(UUID, UUID, VARCHAR, VARCHAR, VARCHAR, VARCHAR, INT, INT, VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS tracking.sp_update_vehicle(UUID, UUID, VARCHAR, VARCHAR, VARCHAR, VARCHAR, INT, INT, VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS tracking.sp_list_vehicles(UUID, UUID, VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS tracking.sp_get_vehicle(UUID, UUID);
DROP FUNCTION IF EXISTS tracking.sp_delete_vehicle(UUID, UUID);
