DROP FUNCTION IF EXISTS tracking.sp_create_rider(UUID, UUID, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, UUID, VARCHAR, VARCHAR, VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS tracking.sp_update_rider(UUID, UUID, VARCHAR, VARCHAR, VARCHAR, VARCHAR, UUID, VARCHAR, VARCHAR, VARCHAR, VARCHAR, BOOLEAN);
DROP FUNCTION IF EXISTS tracking.sp_list_riders(UUID, UUID, UUID, VARCHAR, BOOLEAN);
DROP FUNCTION IF EXISTS tracking.sp_get_rider(UUID, UUID, UUID);
DROP FUNCTION IF EXISTS tracking.sp_delete_rider(UUID, UUID);
