DROP FUNCTION IF EXISTS inventory.sp_create_batch(UUID, VARCHAR, DATE, DATE, DECIMAL, DECIMAL) CASCADE;
DROP FUNCTION IF EXISTS inventory.sp_create_batch(UUID, VARCHAR, DATE, DATE, NUMERIC, NUMERIC) CASCADE;
